require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "vendor/**/*"

Style/Documentation:
  Exclude:
    - "app/models/application_record.rb"
    - "app/helpers/**/*"
    - "test/**/*"

Lint/MissingSuper:
  Enabled: false
  
Metrics/MethodLength:
  Exclude:
    - "test/**/*"