# Postgres environment for local development
version: "3.1"

services:
  db:
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_USER: "template"
      POSTGRES_PASSWORD: "template"
    ports:
      - "15432:5432"
